EMOTION_MAPPING_11 = {
    "happiness": "happy",
    "happy": "happy",
    "fun": "happy",
    "joy": "happy",
    "disappointment": "sad",
    "grief": "sad",
    "remorse": "sad",
    "sad": "sad",
    "sadness": "sad",
    "anger": "anger",
    "hate": "anger",
    "fear": "fear",
    "guilt": "fear",
    "surprise": "surprise",
    "realization": "surprise",
    "annoyance": "disgust",
    "boredom": "disgust",
    "disapproval": "disgust",
    "disgust": "disgust",
    "caring": "love",
    "desire": "love",
    "gratitude": "love",
    "love": "love",
    "admiration": "excitement",
    "amusement": "excitement",
    "curiosity": "excitement",
    "enthusiasm": "excitement",
    "excitement": "excitement",
    "confusion": "anxiety",
    "embarrassment": "anxiety",
    "nervousness": "anxiety",
    "shame": "anxiety",
    "worry": "anxiety",
    "approval": "contentment",
    "optimism": "contentment",
    "pride": "contentment",
    "relief": "contentment",
    "empty": "neutral",
    "neutral": "neutral",
}

EMOTION_VALENCE_AROUSAL = {
    'admiration': (0.9, 0.3),
    'amusement': (0.8, 0.7),
    'anger': (-0.9, 0.9),
    'annoyance': (-0.7, 0.7),
    'approval': (0.8, 0.3),
    'boredom': (-0.8, 0.3),
    'caring': (0.8, 0.3),
    'confusion': (-0.7, 0.7),
    'curiosity': (0.7, 0.7),
    'desire': (0.7, 0.8),
    'disappointment': (-0.8, 0.7),
    'disapproval': (-0.8, 0.7),
    'disgust': (-0.9, 0.8),
    'embarrassment': (-0.7, 0.7),
    'empty': (-0.6, 0.3),
    'enthusiasm': (0.8, 0.8),
    'excitement': (0.9, 0.9),
    'fear': (-0.9, 0.9),
    'fun': (0.8, 0.7),
    'gratitude': (0.9, 0.3),
    'grief': (-0.9, 0.7),
    'guilt': (-0.8, 0.7),
    'happiness': (0.9, 0.8),
    'happy': (0.9, 0.8),
    'hate': (-0.9, 0.9),
    'joy': (0.9, 0.9),
    'love': (0.9, 0.8),
    'nervousness': (-0.7, 0.8),
    'neutral': (0.0, 0.0),
    'optimism': (0.9, 0.7),
    'pride': (0.8, 0.7),
    'realization': (0.8, 0.7),
    'relief': (0.8, 0.3),
    'remorse': (-0.8, 0.7),
    'sad': (-0.9, 0.7),
    'sadness': (-0.9, 0.7),
    'shame': (-0.7, 0.7),
    'surprise': (0.8, 0.9),
    'worry': (-0.8, 0.8),
}
